### ISSUE TITLE
[Question] How to run on emulator/device

### ISSUE THREAD

**Issue by Sjoerrdd** [kematzy/ionic4-vue-app-sidemenu#1]
Hi,
How can I built the application?
When I run `ionic cordova run android`, I get the following error:

` [ERROR] Sorry! ionic cordova run can only be run in an Ionic project directory. `

**Comment by kematzy** [comment]
Hi, I missed your question until now.

I am unable to help you with this issue, and I'm sure you may have solved it already.

I was just interested in Ionic & Vue working together, and couldn't find enough good sources, so I created one trial myself, and then shared it with others.
